### ISSUE TITLE
Cannot start container: port has already been allocated

### ISSUE THREAD

**Issue by seandst** [seandst/webdriver-wharf#2]
```
[ERROR] apscheduler.executors.default Job "balance_containers (trigger: interval[6:00:00], next run at: 2014-09-10 22:30:41 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/apscheduler/executors/base.py", line 108, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/lib/python2.7/site-packages/webdriver_wharf/app.py", line 289, in balance_containers
    interactions.start(container_to_start)
  File "/usr/lib/python2.7/site-packages/webdriver_wharf/interactions.py", line 98, in start
    client.start(container.id, privileged=True, port_bindings=container.port_bindings)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 818, in start
    self._raise_for_status(res)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 87, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 500 Server Error: Internal Server Error ("Cannot start container 299c48ee3416de1bc27c9e153f52ab49a609631edd20a049a721a678dd3e1879: port has already been allocated")
```

This is happened when wharf believes a container has been destroyed, but docker is still in the process of tearing it down. Unfortunately it breaks the entire balance_containers run, so we probably need to guard against APIError and just have balance_containers sleep a second and continue.

**Comment by seandst** [comment]
Indeed, since moving up to rhel 7.1 and picking up the version of docker from that release, this issue has not reappeared.
